from __future__ import annotations

from typing import Any, Protocol


class Repository(Protocol):
    def load_all(self, collection_name: str) -> list[dict[str, Any]]: ...

    def save_all(self, collection_name: str, data: list[dict[str, Any]]) -> None: ...

    def get_by_id(self, collection_name: str, item_id: str | int) -> dict[str, Any] | None: ...

    def create(self, collection_name: str, item: dict[str, Any]) -> dict[str, Any]: ...

    def insert(self, collection_name: str, item: dict[str, Any]) -> dict[str, Any]: ...

    def update(self, collection_name: str, item_id: str | int, patch: dict[str, Any]) -> dict[str, Any]: ...

    def update_where(self, collection_name: str, filters: dict[str, Any], patch: dict[str, Any]) -> int: ...

    def delete(self, collection_name: str, item_id: str | int) -> None: ...

    def delete_where(self, collection_name: str, filters: dict[str, Any]) -> int: ...

    def transaction(self): ...

    def lock_by_id(self, collection_name: str, item_id: str | int) -> dict[str, Any] | None: ...
